alter TABLE T_NOTIFY_LINE add INDEX `FK_T_NOTIFY_LINE_TYPE` (`TYPE`);
alter TABLE T_NOTIFY_LINE add INDEX `FK_T_NOTIFY_LINE_USER_TYPE` (`TYPE`,NOTIFIEDUSER_BASIC_USER_ID);

alter TABLE t_todo add INDEX `FK_T_TODO_STATUS` (`STATUS`);
alter TABLE t_todo add INDEX `FK_T_TODO_ASSIGN_USER_STATUS` (`STATUS`,ASSGINEDUSER_BASIC_USER_ID);
