INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (1, '2013-06-23 14:24:53', '2013-06-23 14:24:53', 'Because we change the data structure for all models, so we have to rebuild the database. But we will keep the release note.', '0', 'Rebuild the database', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (2, '2013-06-23 14:25:20', '2013-06-23 14:25:20', '<div>1. New insurance broker application.</div><div>2. Common global fuzzy search function for search template.</div><div>3. Entity reference search field for many-to-one relationship.</div><div>4. Mocha report service and Junit test case.</div>', '2', 'Release Notes for Mocha Platform 1.0.8', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (3, '2013-06-23 14:25:37', '2013-06-23 14:25:37', '<div>1. Demo sample of Mocha Common Report in CRM testing app.</div><div>2. Change the topic editor to richText in publisher.</div><div>3. Entity card of search template support subEntity.field...</div><div>4. Entity card support codetable value.</div><div>5. Topic card support editable in feed list, notification and forum topic list.</div>', '2', 'Release Notes for Mocha Platform 1.0.9', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (4, '2013-06-23 14:35:19', '2013-06-23 14:35:19', '1. New chat function.<div>2. Support insurance broker customer to login Mocha Platform and display his policies and claims information.</div><div>3. Getting start guide for new user.</div>', '2', 'Release Notes for Mocha Platform 1.1.0', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (6, '2013-06-25 14:56:06', '2013-06-25 14:56:06', 'Some functions need notified user by email.<div>1. Create a new status, forum topic and to-do task, the notified users and related users of todo will be send an email.</div><div>2. New user creating will send an email to notify the login information.</div><div>3. All reply will be send email to notify all repliers.</div><div>4. The notification rule can be&nbsp;configurable&nbsp;for every user in his profile.<span class="Apple-tab-span" style="white-space:pre">									</span></div>', '0', 'Email notification for each function.', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (7, '2013-07-01 02:19:10', '2013-07-08 08:34:25', '<div>1. Common Report: User can create and view report within each application area. Enhance the Domain Model Generator for the report service. Finish first report function for FA application.Create Report button does not work.Report metadata XML structure definition and data generator.</div><div>2. WebChat:Fix the width issue of message bubble.Support enter to post message when choose the checkbox.</div><div>3. Email Notify: Mocha Email framework.User Register email notification template.Message Notify email notification template.</div><div>4. Financial Advisor App: Change the Insurance Broker app to Financial Advisor App.Enhance the customer view page. Add the General Insurance, Life Insurance, Investment and Morgage tab items.</div><div><br></div>', '1', 'Release Notes for Mocha Platform 1.1.1', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (8, '2013-07-05 08:16:43', '2013-07-05 08:16:43', '<p>How do we plan to ensure Data Protection and Privacy of all customer related data?</p><p>1) Within each App that we design and develop. That each user can see only what he is supposed to see.</p><p>2) Encryption of sensitive data. (e.g. Credit Card numbers etc)</p>', '0', 'Data Protection and Privacy', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (9, '2013-07-05 08:17:32', '2013-07-05 08:17:32', 'Some recommendations for the look and feel of the website. Please refer to the document attached.', '0', 'Recommendations for site enhancements', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (10, '2013-07-08 08:31:38', '2013-07-08 08:31:38', '1. New App E-Commerce structure.<div>2. Integrate with eBay API for order management function in e-commerce app.</div><div>3. A read-only version of Mocha Mobile version.</div>', '0', 'Release Notes for Mocha Platform 1.1.2', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (11, '2013-07-11 16:30:52', '2013-07-11 16:30:52', 'Please refer to this video that I saw in the US. This is an example of how this company called Five9 integrates with Sales force.', '0', 'Sales force integration example', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (12, '2013-07-11 17:23:04', '2013-07-11 17:23:04', '<p><a href="http://www.rewardprograms.org/thefreegeek/features/wide-open-wallet-50-awesome-open-source-financial-tools.html">http://www.rewardprograms.org/thefreegeek/features/wide-open-wallet-50-awesome-open-source-financial-tools.html</a></p><p><a href="http://www.smallbusinesscomputing.com/News/Software/5-top-open-source-financial-apps-for-small-business.html">http://www.smallbusinesscomputing.com/News/Software/5-top-open-source-financial-apps-for-small-business.html</a></p>', '0', 'Websites for financial servcies (open source solutions)', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (15, '2013-07-14 09:01:26', '2013-07-14 09:03:17', '1. Notification can display the new notify number and it will load by time.<div>2. New webchat for whole platform to provide a quick multi-chat in anywhere.</div><div>3. Add eBay auth page.</div><div>4. Order integration with eBay.</div><div>5. Fix some known issues of Mocha Platform.</div>', '0', 'Release Notes for Mocha Platform 1.1.3', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (16, '2013-07-15 14:35:03', '2013-07-15 14:35:03', '<p>Hi Coral and Vance,</p><p>Here is the linkedin API information,&nbsp;that we were discussing to get customer information.</p><p><a href="http://developer.linkedin.com/apis">http://developer.linkedin.com/apis</a></p><p>Regards</p><p>Mildred</p>', '2', 'Linkedin API', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (20, '2013-07-17 14:44:31', '2013-07-17 14:44:31', '<p>Hi Coral and Vance,</p><p>Can you explain to me how the integraton with eBay work? Right now what I see is that there is only one selection that you can make. Example (only eBay or only Amazon U.K.). There is always a possibility that a customer has more than one selection (i.e. eBay, AmazonU.K or more).</p><p>Can you also explain how the process will work?</p>', '1', 'Ecommerce App', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (22, '2013-07-17 23:39:43', '2013-07-17 23:39:43', '<p>I like this statement in the CRM document that I sent to you. I think our goal and focus should always be this.</p><i><font color="#231f20" size="2" face="Whitman-ItalicLF"><font color="#231f20" size="2" face="Whitman-ItalicLF"><font color="#231f20" size="2" face="Whitman-ItalicLF"><p align="LEFT">“It keeps us all on the same page. We can all see a client, know what communication has taken place, what campaigns that individual is involved in, who spoke with them last and what it was regarding, what groups of clients that individual fits in with, and who that client is linked to (e.g., relatives, referrers, bankers, CPAs, etc.)&nbsp;</font></font></font></i></p>', '0', 'A note to share', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (23, '2013-07-21 15:06:36', '2013-07-22 01:57:38', '1. Linkedin API integration with auth.<div>2. Enhance the notification for reply function.</div><div>3. Add the official email notification by all notify message.</div><div>4. A basic structure for Mocha Platform Mobile Version.</div><div>5. Enable the https protocol for Mocha Platform.</div><div>Please use the https to visit our website&nbsp;<a href="https://www.mocha-platform.com/cooperate/">https://www.mocha-platform.com/cooperate/</a></div><div>Please check the Mobile version URL in iPhone Safari and Android Chrome</div><div>with the URL:&nbsp;<a href="http://mobile.mocha-platform.com/cmobile/">http://mobile.mocha-platform.com/cmobile/</a></div>', '2', 'Release Notes for Mocha Platform 1.1.4', -3);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (24, '2013-07-24 11:27:03', '2013-07-24 11:27:03', '<p>Here is an update on how we can use Excel as a rating engine for our customers.</p><p>Here is also a website which provides an api for excel.</p><p><a href="http://www.andykhan.com/jexcelapi/tutorial.html">http://www.andykhan.com/jexcelapi/tutorial.html</a></p>', '0', 'Excel as a rating engine', -4);
INSERT INTO `t_discuss` (`DISCUSS_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CONTENT`, `STATUS`, `TITLE`, `CREATOR_BASIC_USER_ID`) VALUES (25, '2013-07-31 14:48:37', '2013-07-31 14:48:37', '<div>User experience is very important to us. Performance is one of the important factors we focus on improving continuously. &nbsp;We also believe a good website is fast and user-friendly.&nbsp;</div><div><br></div><div>Before we start to tune our application performance, we can isolation our system architecture to different level : db, JVM, backend code, OS, DNS/CDN, webServer/AppServer, etc. So first, we will make our JVM/DB/WebServer/AppServer configure properly. Here I list something in my mind will check first:</div><div><ul><li>&nbsp;java options (gc allgorithm, gc log, heapdump setting, jmx enabled)</li><li>&nbsp;mysql system level setting&nbsp;</li><li>App Server (connection pool, etc)</li><li>Web Server (thread pool, static files cache setting, gzip, etc)</li></ul></div>', '0', 'Performance is a feature', -2);


INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (1, '2013-06-23 14:24:53', '2013-06-23 14:24:53', -3, 1, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (2, '2013-06-23 14:25:20', '2013-06-23 14:25:20', -3, 2, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (3, '2013-06-23 14:25:37', '2013-06-23 14:25:37', -3, 3, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (4, '2013-06-23 14:35:19', '2013-06-23 14:35:19', -3, 4, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (8, '2013-06-25 14:56:06', '2013-06-25 14:56:06', -3, 6, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (11, '2013-07-01 02:19:10', '2013-07-01 02:19:10', -3, 7, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (14, '2013-07-05 08:16:43', '2013-07-05 08:16:43', -4, 8, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (15, '2013-07-05 08:17:32', '2013-07-05 08:17:32', -4, 9, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (16, '2013-07-08 08:31:38', '2013-07-08 08:31:38', -3, 10, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (17, '2013-07-11 16:30:52', '2013-07-11 16:30:52', -4, 11, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (18, '2013-07-11 17:23:04', '2013-07-11 17:23:04', -4, 12, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (21, '2013-07-14 09:01:26', '2013-07-14 09:01:26', -3, 15, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (22, '2013-07-15 14:35:03', '2013-07-15 14:35:03', -4, 16, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (26, '2013-07-17 14:44:31', '2013-07-17 14:44:31', -4, 20, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (28, '2013-07-17 23:39:43', '2013-07-17 23:39:43', -4, 22, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (29, '2013-07-21 15:06:36', '2013-07-21 15:06:36', -3, 23, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (30, '2013-07-24 11:27:03', '2013-07-24 11:27:03', -4, 24, NULL, NULL);
INSERT INTO `t_time_line` (`TIME_LINE_ID`, `C_CREATTIME`, `C_LASTMODIFIEDTIME`, `CREATOR_BASIC_USER_ID`, `DISCUSS_DISCUSS_ID`, `STATUS_STATUS_ID`, `TODO_TO_DO_ID`) VALUES (33, '2013-07-31 14:48:37', '2013-07-31 14:48:37', -2, 25, NULL, NULL);

UPDATE SEQUENCE t SET t.SEQ_COUNT='100' WHERE t.SEQ_NAME IN ('TIMELINEID_SEQ','DISCUSSID_SEQ');

