package com.coral.vaadin.template;

import com.coral.foundation.constant.SystemConstant;
import com.coral.foundation.md.model.Entity;
import com.coral.foundation.md.model.Mocha;
import com.coral.foundation.md.model.helper.VGenHelper;
import com.coral.foundation.utils.StrUtils;
import java.util.List;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class TSearchPresenter {
  private Entity entity;
  
  private List<Mocha> corals;
  
  private String searchPresenterClassName;
  
  private String searchListenerName;
  
  private String entityName;
  
  private String entityVariable;
  
  private String entityDaoIntf;
  
  private String daoIntfPackage;
  
  private String createViewClassName;
  
  public String init(final Entity entity, final List<Mocha> corals) {
    String _xblockexpression = null;
    {
      this.entity = entity;
      this.corals = corals;
      this.entityName = entity.entityName;
      String _lowCaseFirstLetter = StrUtils.lowCaseFirstLetter(this.entityName);
      this.entityVariable = _lowCaseFirstLetter;
      String _genSearchPresenterClassName = VGenHelper.genSearchPresenterClassName(this.entityName);
      this.searchPresenterClassName = _genSearchPresenterClassName;
      String _genSearchListenerName = VGenHelper.genSearchListenerName(this.entityName);
      this.searchListenerName = _genSearchListenerName;
      String _genDaoIntf = VGenHelper.genDaoIntf(this.entityName);
      this.entityDaoIntf = _genDaoIntf;
      final Mocha currentCoral = VGenHelper.getCurrentCoral(entity, corals);
      String _daoIntfPackage = currentCoral.getDaoIntfPackage();
      this.daoIntfPackage = _daoIntfPackage;
      String _genCreateViewClassName = VGenHelper.genCreateViewClassName(this.entityName);
      String _createViewClassName = this.createViewClassName = _genCreateViewClassName;
      _xblockexpression = (_createViewClassName);
    }
    return _xblockexpression;
  }
  
  public CharSequence generate() {
    StringConcatenation _builder = new StringConcatenation();
    CharSequence _GENPackageImport = this.GENPackageImport();
    _builder.append(_GENPackageImport, "");
    _builder.newLineIfNotEmpty();
    CharSequence _GENClassHead = this.GENClassHead();
    _builder.append(_GENClassHead, "");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _GENBuildVeriable = this.GENBuildVeriable();
    _builder.append(_GENBuildVeriable, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _GENConstructor = this.GENConstructor();
    _builder.append(_GENConstructor, "	");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _GENBuildMethod = this.GENBuildMethod();
    _builder.append(_GENBuildMethod, "	");
    _builder.newLineIfNotEmpty();
    CharSequence _GENClassEnd = this.GENClassEnd();
    _builder.append(_GENClassEnd, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public CharSequence GENPackageImport() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    _builder.append(SystemConstant.TSEARCH_PRESENTER_PKG, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.Collection;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import ");
    String _currentEntityPackage = VGenHelper.getCurrentEntityPackage(this.entity, this.corals);
    String _plus = (_currentEntityPackage + ".*");
    _builder.append(_plus, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _plus_1 = (SystemConstant.TSEARCH_LISTENER_PKG + ".*");
    _builder.append(_plus_1, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _plus_2 = (this.daoIntfPackage + ".*");
    _builder.append(_plus_2, "");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("import com.coral.vaadin.controller.Presenter;");
    _builder.newLine();
    _builder.append("import com.coral.vaadin.widget.Viewer;");
    _builder.newLine();
    _builder.append("import com.coral.vaadin.widget.listener.*;");
    _builder.newLine();
    _builder.append("import com.coral.vaadin.controller.PageChangeEvent;");
    _builder.newLine();
    _builder.append("import com.coral.vaadin.widget.table.AbstractTable;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.Component;");
    _builder.newLine();
    _builder.append("import com.coral.foundation.core.impl.MochaEventBus;");
    _builder.newLine();
    _builder.append("import com.coral.foundation.spring.bean.SpringContextUtils;");
    _builder.newLine();
    _builder.append("import org.vaadin.dialogs.ConfirmDialog;");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence GENClassHead() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* ");
    _builder.append(this.searchPresenterClassName, "  ");
    _builder.append(" is a auto Generated class. Please don\'t modify it.");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("* @author Coral");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(this.searchPresenterClassName, "");
    _builder.append(" extends AbstractActionListener implements Presenter, ");
    _builder.append(this.searchListenerName, "");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = ");
    String _genserialVersionUID = VGenHelper.genserialVersionUID();
    _builder.append(_genserialVersionUID, "	");
    _builder.append("L;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence GENBuildVeriable() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("private Viewer viewer;");
    _builder.newLine();
    _builder.append("private MochaEventBus eventBus;");
    _builder.newLine();
    _builder.append("private ");
    _builder.append(this.entityDaoIntf, "");
    _builder.append(" dao = SpringContextUtils.getBean(");
    _builder.append(this.entityDaoIntf, "");
    _builder.append(".class);");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence GENConstructor() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public ");
    _builder.append(this.searchPresenterClassName, "");
    _builder.append("(Viewer viewer, MochaEventBus eventBus) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("this.viewer = viewer;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("this.eventBus = eventBus;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("viewer.setListener(this);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("viewer.build();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("clean();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence GENBuildMethod() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public Component go() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return (Component)viewer;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public void setEditValue(Long id) {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// ignore in search Presenter.");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* Query a list result of ");
    _builder.append(this.entityName, "  ");
    _builder.append(".");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public void query() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* Show all result of ");
    _builder.append(this.entityName, "  ");
    _builder.append(".");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public void clean() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("List<");
    _builder.append(this.entityName, "	");
    _builder.append("> valueList = dao.findAll();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("AbstractTable table = viewer.getTables().get(0);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("table.setValue(valueList);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("table.refreshRowCache();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* Add a new ");
    _builder.append(this.entityName, "  ");
    _builder.append(".");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public void add() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("eventBus.post(new PageChangeEvent(\"");
    _builder.append(this.createViewClassName, "	");
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* Edit a exited ");
    _builder.append(this.entityName, "  ");
    _builder.append(".");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public void edit() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append(this.entityName, "	");
    _builder.append(" value = (");
    _builder.append(this.entityName, "	");
    _builder.append(") getSelectedEntity();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("if(value != null) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("eventBus.post(new PageChangeEvent(\"");
    _builder.append(this.createViewClassName, "		");
    _builder.append("\",value.getID()));");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("* Remove a ");
    _builder.append(this.entityName, "  ");
    _builder.append("CreateView.");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("public void delete() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("final ");
    _builder.append(this.entityName, "	");
    _builder.append(" value = (");
    _builder.append(this.entityName, "	");
    _builder.append(") getSelectedEntity();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("if(value != null) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ConfirmDialog.show(viewer.getWindow(), \"\u8BF7\u786E\u8BA4\",\"\u60A8\u662F\u5426\u771F\u7684\u8981\u5220\u9664\u8FD9\u6761\u6570\u636E?\", \"\u662F\u7684\", \"\u53D6\u6D88\",new ConfirmDialog.Listener() {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public void onClose(ConfirmDialog dialog) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (dialog.isConfirmed()) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("dao.remove(value.getID());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("viewer.getTables().get(0).getTable().removeItem(value);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("});");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public ");
    _builder.append(this.entityName, "");
    _builder.append(" getSelectedEntity() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("AbstractTable table = viewer.getTables().get(0);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("Collection<Object> selections = table.getTable().getSelection();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if(selections.size() > 0) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append(this.entityName, "		");
    _builder.append(" value = (");
    _builder.append(this.entityName, "		");
    _builder.append(")selections.iterator().next();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return value;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence GENClassEnd() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
